modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/BiomeInfo/blob/1.16/LICENSE"

[[mods]] #mandatory
	modId="biomeinfo" #mandatory
	version="${version}" #mandatory
	displayName="BiomeInfo" #mandatory
	description='''Shows the current biome, without F3 overlay enabled.''' #mandatory
	issueTrackerURL="http://github.com/bl4ckscor3/BiomeInfo/issues"
	displayURL="http://minecraft.curseforge.com/projects/biomeinfo"
	authors="bl4ckscor3"

[[dependencies.biomeinfo]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.biomeinfo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"